server:
  port: 8080

logging:
  level:
    org.springframework.web.client: DEBUG
    org.apache.http: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

comfy:
  ui:
    url: https://localhost:8188/api