server:
  port: 8080

logging:
  level:
    org.springframework.web.client: DEBUG
    org.apache.http: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

comfy:
  ui:
    url: https://localhost:8188/api
master:
  callback:
    url: http://38.150.67.180:8080/api/v1/tasks/callback